import { CourseInterface } from "../classes/types/types";

export const courseMockup: CourseInterface[] = [
  {
    id: "pTOUU",
    title: "Vivyan",
    stream: "vestibulum",
    type: "montes",
    startDate: "12/22/2021",
    endDate: "6/21/2022",
    trainers: [],
  },
  {
    id: "YhJnQ",
    title: "Bryn",
    stream: "sit",
    type: "morbi",
    startDate: "12/8/2022",
    endDate: "4/15/2022",
    trainers: [],
  },
  {
    id: "58W09",
    title: "Hoyt",
    stream: "tellus",
    type: "pulvinar",
    startDate: "7/1/2022",
    endDate: "9/17/2022",
    trainers: [],
  },
  {
    id: "5q9vR",
    title: "Darb",
    stream: "erat",
    type: "vitae",
    startDate: "8/30/2022",
    endDate: "6/12/2022",
    trainers: [],
  },
  {
    id: "Y6j9K",
    title: "Jephthah",
    stream: "amet",
    type: "at",
    startDate: "3/28/2022",
    endDate: "7/21/2022",
    trainers: [],
  },
  {
    id: "T4Hcf",
    title: "David",
    stream: "nisl",
    type: "turpis",
    startDate: "3/30/2022",
    endDate: "10/28/2022",
    trainers: [],
  },
  {
    id: "y3OQ9",
    title: "Cammy",
    stream: "hac",
    type: "fusce",
    startDate: "8/9/2022",
    endDate: "6/27/2022",
    trainers: [],
  },
  {
    id: "q2nDO",
    title: "Bendite",
    stream: "tellus",
    type: "dictumst",
    startDate: "1/11/2022",
    endDate: "9/4/2022",
    trainers: [],
  },
  {
    id: "fsz5k",
    title: "Jehu",
    stream: "augue",
    type: "in",
    startDate: "3/9/2022",
    endDate: "3/26/2022",
    trainers: [],
  },
  {
    id: "w8Cb2",
    title: "Allie",
    stream: "neque",
    type: "convallis",
    startDate: "12/5/2022",
    endDate: "4/13/2022",
    trainers: [],
  },
];
