import { CourseInterface } from "../classes/types/types";

export const courseMockup: CourseInterface[] = [
  {
    id: "pTOUU",
    title: "Java",
    stream: "Java",
    type: "part time",
    startDate: "12/22/2021",
    endDate: "",
    cost: 2000,
    trainers: [],
    students: [],
  },
  {
    id: "YhJnQ",
    title: "Java",
    stream: "Java",
    type: "full time",
    startDate: "12/8/2022",
    endDate: "",
    cost: 2000,
    trainers: [],
    students: [],
  },
  {
    id: "58W09",
    title: "C++",
    stream: "C++",
    type: "part time",
    startDate: "1/7/2022",
    endDate: "",
    cost: 2000,
    trainers: [],
    students: [],
  },
  {
    id: "5q9vR",
    title: "C++",
    stream: "C++",
    type: "full time",
    startDate: "8/30/2022",
    endDate: "",
    cost: 2500,
    trainers: [],
    students: [],
  },
  {
    id: "Y6j9K",
    title: "Python",
    stream: "Python",
    type: "part time",
    startDate: "3/28/2022",
    endDate: "",
    cost: 2000,
    trainers: [],
    students: [],
  },
  {
    id: "T4Hcf",
    title: "Python",
    stream: "Python",
    type: "full time",
    startDate: "3/30/2022",
    endDate: "",
    cost: 2500,
    trainers: [],
    students: [],
  },
  {
    id: "y3OQ9",
    title: "Javascript",
    stream: "Javascript",
    type: "part time",
    startDate: "9/6/2022",
    endDate: "",
    cost: 2000,
    trainers: [],
    students: [],
  },
  {
    id: "q2nDO",
    title: "Javascript",
    stream: "Javascript",
    type: "full time",
    startDate: "11/1/2022",
    endDate: "",
    cost: 2000,
    trainers: [],
    students: [],
  },
];
