import { CourseInterface } from "../classes/types/types";

export const courseMockup: CourseInterface[] = [
  {
    id: "pTOUU",
    title: "Java",
    stream: "Java",
    type: "Part_Time",
    startDate: "12/22/2021",
    endDate: "6/21/2022",
    cost: 2000,
    trainers: [],
    students: [],
  },
  {
    id: "YhJnQ",
    title: "Java",
    stream: "Java",
    type: "Full_Time",
    startDate: "12/8/2022",
    endDate: "4/15/2022",
    cost: 2000,
    trainers: [],
    students: [],
  },
  {
    id: "58W09",
    title: "C++",
    stream: "C++",
    type: "Part_Time",
    startDate: "7/1/2022",
    endDate: "9/17/2022",
    cost: 2000,
    trainers: [],
    students: [],
  },
  {
    id: "5q9vR",
    title: "C++",
    stream: "C++",
    type: "Full_Time",
    startDate: "8/30/2022",
    endDate: "6/12/2022",
    cost: 2500,
    trainers: [],
    students: [],
  },
  {
    id: "Y6j9K",
    title: "Python",
    stream: "Python",
    type: "Part_Time",
    startDate: "3/28/2022",
    endDate: "7/21/2022",
    cost: 2000,
    trainers: [],
    students: [],
  },
  {
    id: "T4Hcf",
    title: "Python",
    stream: "Python",
    type: "Full_Time",
    startDate: "3/30/2022",
    endDate: "10/28/2022",
    cost: 2500,
    trainers: [],
    students: [],
  },
  {
    id: "y3OQ9",
    title: "Javascript",
    stream: "Javascript",
    type: "Part_Time",
    startDate: "6/9/2022",
    endDate: "12/27/2022",
    cost: 2000,
    trainers: [],
    students: [],
  },
  {
    id: "q2nDO",
    title: "Javascript",
    stream: "Javascript",
    type: "Full_Time",
    startDate: "1/11/2022",
    endDate: "9/4/2022",
    cost: 2000,
    trainers: [],
    students: [],
  },
];
