import { StudentInterface } from "../classes/types/types";

export const studentMockup: StudentInterface[] = [
  {
    id: "ZFg15",
    firstName: "Thanos",
    lastName: "Tsoustas",
    dateOfBirth: "11/7/1997",
    tuitionFees: 2067,
    assignments: [],
    course: [],
  },
  {
    id: "NtlUe",
    firstName: "Drusi",
    lastName: "Rewbottom",
    dateOfBirth: "23/6/1998",
    tuitionFees: 1294,
    assignments: [],
    course: [],
  },
  {
    id: "Km2L6",
    firstName: "Warden",
    lastName: "Huison",
    dateOfBirth: "30/6/1998",
    tuitionFees: 2282,
    assignments: [],
    course: [],
  },
  {
    id: "oICSG",
    firstName: "Crin",
    lastName: "Mackro",
    dateOfBirth: "19/12/2008",
    tuitionFees: 2275,
    assignments: [],
    course: [],
  },
  {
    id: "sLIRb",
    firstName: "Briney",
    lastName: "Cicco",
    dateOfBirth: "13/7/2011",
    tuitionFees: 1738,
    assignments: [],
    course: [],
  },
  {
    id: "VpWEp",
    firstName: "Eda",
    lastName: "Reinhardt",
    dateOfBirth: "9/6/1998",
    tuitionFees: 766,
    assignments: [],
    course: [],
  },
  {
    id: "fl42d",
    firstName: "Atalanta",
    lastName: "Sinnie",
    dateOfBirth: "6/12/1994",
    tuitionFees: 1693,
    assignments: [],
    course: [],
  },
  {
    id: "7gYGv",
    firstName: "Antonina",
    lastName: "Devitt",
    dateOfBirth: "27/8/2004",
    tuitionFees: 789,
    assignments: [],
    course: [],
  },
  {
    id: "ApDJx",
    firstName: "Jaynell",
    lastName: "Goodlet",
    dateOfBirth: "1/3/2018",
    tuitionFees: 2271,
    assignments: [],
    course: [],
  },
  {
    id: "SJc5z",
    firstName: "Gabriella",
    lastName: "Steen",
    dateOfBirth: "28/5/2013",
    tuitionFees: 1264,
    assignments: [],
    course: [],
  },
];
