import { StudentInterface } from "../classes/types/types";

export const studentMockup: StudentInterface[] = [
  {
    id: "ZFg15",
    firstName: "Tillie",
    lastName: "McCafferky",
    dateOfBirth: "7/11/1997",
    tuitionFees: 2067,
    assignments: [],
    course: [],
  },
  {
    id: "NtlUe",
    firstName: "Drusi",
    lastName: "Rewbottom",
    dateOfBirth: "6/23/1998",
    tuitionFees: 1294,
    assignments: [],
    course: [],
  },
  {
    id: "Km2L6",
    firstName: "Warden",
    lastName: "Huison",
    dateOfBirth: "6/30/1998",
    tuitionFees: 2282,
    assignments: [],
    course: [],
  },
  {
    id: "oICSG",
    firstName: "Crin",
    lastName: "Mackro",
    dateOfBirth: "12/19/2008",
    tuitionFees: 2275,
    assignments: [],
    course: [],
  },
  {
    id: "sLIRb",
    firstName: "Briney",
    lastName: "Cicco",
    dateOfBirth: "7/13/2011",
    tuitionFees: 1738,
    assignments: [],
    course: [],
  },
  {
    id: "VpWEp",
    firstName: "Eda",
    lastName: "Reinhardt",
    dateOfBirth: "6/9/1998",
    tuitionFees: 766,
    assignments: [],
    course: [],
  },
  {
    id: "fl42d",
    firstName: "Atalanta",
    lastName: "Sinnie",
    dateOfBirth: "12/6/1994",
    tuitionFees: 1693,
    assignments: [],
    course: [],
  },
  {
    id: "7gYGv",
    firstName: "Antonina",
    lastName: "Devitt",
    dateOfBirth: "8/27/2004",
    tuitionFees: 789,
    assignments: [],
    course: [],
  },
  {
    id: "ApDJx",
    firstName: "Jaynell",
    lastName: "Goodlet",
    dateOfBirth: "3/1/2018",
    tuitionFees: 2271,
    assignments: [],
    course: [],
  },
  {
    id: "SJc5z",
    firstName: "Gabriella",
    lastName: "Steen",
    dateOfBirth: "5/28/2013",
    tuitionFees: 1264,
    assignments: [],
    course: [],
  },
];
